[package]
name = "memcopy"
version = "0.1.0"
edition = "2021"

[features]
default = []
tsx = ["dep:libc"]

[dependencies]
libc = { version = "0.2", optional = true }

[[bin]]
name = "memcopy"
path = "src/main.rs"
