[package]
name = "memcopy"
version = "0.1.0"
edition = "2021"

[lib]
name = "memcopy"
path = "src/lib.rs"

[dependencies]
libc = { version = "0.2", optional = false }
rand = "0.8"

[[bin]]
name = "memcopy"
path = "src/main.rs"

[features]
default = []
tsx = []
fault = []
